package:
  name: pycifrw
  version: "4.4"

source:
  fn: PyCifRW-4.4.tar.gz
  url: https://files.pythonhosted.org/packages/4c/ab/b4842d450c06104c3f037c391a1ac5165e677b1226b44bc47a0b9cbc1bd3/PyCifRW-4.4.tar.gz
  sha5: f365ed97991738a99722e08afe772fe197bf7f40dfc0a210d524e7742ad81ff8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycifrw = pycifrw:main
    #
    # Would create an entry point called pycifrw that calls pycifrw.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - CifFile
    - CifFile.drel

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/jamesrhester/pycifrw/overview
  license: Python Software Foundation License
  summary: 'CIF/STAR file support for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
