package:
  name: pyqtgraph
  version: "0.10.0"

source:
  git_url: https://github.com/CPrescher/pyqtgraph
  git_rev: fix_np_expoerter_error

build:
  number: 0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyqtgraph = pyqtgraph:main
    #
    # Would create an entry point called pyqtgraph that calls pyqtgraph.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - pyqt

  run:
    - python
    - numpy
    - scipy
    - pyqt

test:
  # Python imports
  imports:
    - pyqtgraph

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pyqtgraph.org
  license: MIT License
  summary: 'Scientific Graphics and GUI Library for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
