{% set name = "karabo_data" %}
{% set version = "0.7.0" %}

package:
  name: "karabo-data"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "4c2d989cad4a52f0e5fa19dcf41f9021bbd35b08b98e0f015db7d5153e6a51fc"

build:
  number: 0
  entry_points:
    - lsxfel = karabo_data.lsxfel:main
    - karabo-bridge-serve-files = karabo_data.export:main
    - karabo-data-validate = karabo_data.validation:main
    - karabo-data-make-virtual-cxi = karabo_data.cli.make_virtual_cxi:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - cfelpyutils
    - fabio
    - h5py
    - karabo-bridge
    - matplotlib
    - msgpack
    - msgpack-numpy
    - numpy
    - pandas
    - pip
    - python
    - pyzmq 
    - scipy
    - xarray
  run:
    - cfelpyutils 
    - fabio
    - h5py
    - karabo-bridge
    - matplotlib
    - msgpack
    - msgpack-numpy 
    - numpy
    - pandas
    - python
    - pyzmq 
    - scipy
    - xarray

test:
  imports:
    - karabo_data
    - karabo_data.cli
    - karabo_data.geometry2
    - karabo_data.tests
    - karabo_data.tests.cli
    - karabo_data.tests.mockdata
  commands:
    - lsxfel --help
    - karabo-bridge-serve-files --help
    - karabo-data-validate --help
    - karabo-data-make-virtual-cxi --help

about:
  home: "https://github.com/European-XFEL/karabo_data"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Tools to read and analyse data from European XFEL"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - CPrescher
