package:
  name: fabio
  version: "0.7.0"

source:
  git_url: https://github.com/silx-kit/fabio
  git_rev: v0.7.0

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy 1.11.*
        - cython
        - vc 9  # [win and py27]
        - vc 10  # [win and py34]
        - vc 14  # [win and py>=35]
        # could use opencl, but need the package on conda-forge first
        # - opencl

    run:
        - python
        - numpy >=1.11

test:
    imports:
        - fabio
        - fabio.test
        - fabio.third_party

about:
    home: https://github.com/silx-kit/fabio
    license: GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0
    summary: I/O library for images produced by 2D X-ray detector
    license_family: Other
license_file: copyright

about:
  home: http://fable.wiki.sourceforge.net/fabio
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Image IO for fable'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
