package:
  name: fabio
  version: "0.8.0"
  
build:
  number: 1

source:
  git_url: https://github.com/silx-kit/fabio
  git_rev: v0.8.0

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
    host:
        - python
        - pip
        - setuptools
        - numpy
        - cython
        # could use opencl, but need the package on conda-forge first
        # - opencl

    run:
        - python
        - numpy

test:
    imports:
        - fabio
        - fabio.test
        - fabio.third_party

about:
    home: https://github.com/silx-kit/fabio
    license: GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0
    summary: I/O library for images produced by 2D X-ray detector
    license_family: Other
license_file: copyright